parameters:
    pim_prestashop_connector.repository.category.class:                         Pim\Bundle\PrestashopConnectorBundle\Entity\Repository\CategoryRepository
    pim_prestashop_connector.repository.currency.class:                         Pim\Bundle\PrestashopConnectorBundle\Entity\Repository\CurrencyRepository
    pim_prestashop_connector.repository.group.class:                            Pim\Bundle\PrestashopConnectorBundle\Entity\Repository\GroupRepository
    pim_prestashop_connector.repository.delta_product_export.class:             Doctrine\ORM\EntityRepository
    pim_prestashop_connector.repository.delta_product_association_export.class: Doctrine\ORM\EntityRepository
    pim_prestashop_connector.repository.delta_configurable_export.class:        Doctrine\ORM\EntityRepository

services:
    pim_prestashop_connector.repository.category:
        class: %pim_prestashop_connector.repository.category.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.category.class%]
        tags:
            - { name: 'pim_repository' }

    pim_prestashop_connector.repository.delta_product_export:
        class: %pim_prestashop_connector.repository.delta_product_export.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_prestashop_connector.entity.delta_product_export.class%]
        tags:
            - { name: 'pim_repository' }

    pim_prestashop_connector.repository.delta_product_association_export:
        class: %pim_prestashop_connector.repository.delta_product_association_export.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_prestashop_connector.entity.delta_product_association_export.class%]
        tags:
            - { name: 'pim_repository' }

    pim_prestashop_connector.repository.delta_configurable_export:
        class: %pim_prestashop_connector.repository.delta_configurable_export.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_prestashop_connector.entity.delta_configurable_export.class%]
        tags:
            - { name: 'pim_repository' }

    pim_prestashop_connector.repository.group:
        class: %pim_prestashop_connector.repository.group.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_catalog.entity.group.class%]
        tags:
            - { name: 'pim_repository' }
